version: '3.7'

services:
  database:
    container_name: postgres-fireant
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
  backend:
    container_name: app-fireant
    ports:
      - 8000:8000
    build:
      context: ./app
    depends_on: 
      - database

volumes:
  database:
    name: postgres-db
